from gestion_comunicacional.social_activity.entities.SocialActivityEntity import SocialActivityEntity
from gestion_comunicacional.social_media.entities.SocialMediaAccountEntity import SocialMediaAccountEntity
from gestion_comunicacional.social_media.entities.SocialMediaPostEntity import SocialMediaPostEntity

from django.contrib import admin

admin.site.register(SocialMediaAccountEntity)
admin.site.register(SocialMediaPostEntity)
admin.site.register(SocialActivityEntity)
