# Generated by Django 5.0.6 on 2024-06-11 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuadrantePazEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "db_table": "eme_cuadrantes_paz",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstadoEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "db_table": "general_estados",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CiudadEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.estadoentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciudad",
                "verbose_name_plural": "Ciudades",
                "db_table": "general_ciudades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MunicipioEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.estadoentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "db_table": "general_municipios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ParroquiaEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "cuadrante_paz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.cuadrantepazentity",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.municipioentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parroquia",
                "verbose_name_plural": "Parroquias",
                "db_table": "general_parroquias",
                "ordering": ["nombre"],
            },
        ),
    ]
