# Generated by Django 5.0.3 on 2024-07-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario', models.TextField(default='', max_length=64, verbose_name='Descripción:')),
                ('departamento', models.CharField(default='', max_length=64, verbose_name='Serial:')),
                ('descripcion', models.CharField(default='', max_length=64, verbose_name='Marca:')),
                ('articulo', models.CharField(default='', max_length=64, verbose_name='Modelo:')),
                ('cantidad', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.CharField(default='', max_length=64, verbose_name='Garantía:')),
            ],
        ),
        migrations.CreateModel(
            name='Averia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienes', models.TextField(default='', max_length=64, verbose_name='Bienes:')),
                ('sintomas', models.CharField(default='', max_length=64, verbose_name='Sintomas:')),
                ('departamento_ave', models.CharField(default='', max_length=64, verbose_name='Departamento:')),
                ('problema', models.CharField(default='', max_length=64, verbose_name='Problema:')),
                ('condicion', models.CharField(default='', max_length=64, verbose_name='Condición:')),
                ('ubicacion', models.CharField(default='', max_length=64, verbose_name='Ubicación:')),
                ('codigo_bn', models.CharField(default='', max_length=64, verbose_name='Garantía:')),
            ],
        ),
        migrations.CreateModel(
            name='Bienes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='', max_length=64, verbose_name='Descripción:')),
                ('marca', models.CharField(default='', max_length=64, verbose_name='Marca:')),
                ('modelo', models.CharField(default='', max_length=64, verbose_name='Modelo:')),
                ('serial', models.CharField(default='', max_length=64, verbose_name='Serial:')),
                ('cantidad', models.CharField(default='', max_length=64, verbose_name='Cantidad:')),
                ('asignado', models.CharField(default='', max_length=64, verbose_name='Asignado:')),
                ('valor', models.CharField(default='', max_length=64, verbose_name='Valor:')),
                ('condicion', models.CharField(default='', max_length=64, verbose_name='Condición:')),
                ('ubicacion', models.CharField(default='', max_length=64, verbose_name='Ubicación:')),
                ('fecha_adq', models.DateField(verbose_name='Fecha')),
                ('garantia', models.CharField(default='', max_length=64, verbose_name='Garantía:')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.TextField(default='', max_length=64, verbose_name='Descripción:')),
                ('serial', models.CharField(default='', max_length=64, verbose_name='Serial:')),
                ('marca', models.CharField(default='', max_length=64, verbose_name='Marca:')),
                ('modelo', models.CharField(default='', max_length=64, verbose_name='Modelo:')),
                ('fecha_adq', models.DateField(verbose_name='Fecha')),
                ('numero_orden', models.CharField(default='', max_length=64, verbose_name='Condición:')),
                ('valor', models.CharField(default='', max_length=64, verbose_name='Valor:')),
                ('cantidad', models.CharField(default='', max_length=64, verbose_name='Cantidad:')),
                ('proveedor', models.CharField(default='', max_length=64, verbose_name='Asignado:')),
                ('ubicacion', models.CharField(default='', max_length=64, verbose_name='Ubicación:')),
                ('garantia', models.CharField(default='', max_length=64, verbose_name='Garantía:')),
            ],
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='', max_length=64, verbose_name='Descripción:')),
                ('marca', models.CharField(default='', max_length=64, verbose_name='Marca:')),
                ('serial', models.CharField(default='', max_length=64, verbose_name='Serial:')),
                ('cantidad', models.CharField(default='', max_length=64, verbose_name='Cantidad:')),
                ('valor', models.CharField(default='', max_length=64, verbose_name='Valor:')),
                ('condicion', models.CharField(default='', max_length=64, verbose_name='Condición:')),
                ('ubicacion', models.CharField(default='', max_length=64, verbose_name='Ubicación:')),
                ('fecha_adq', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(default='', max_length=64, verbose_name='Garantía:')),
            ],
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='', max_length=64, verbose_name='Descripción:')),
                ('marca', models.CharField(default='', max_length=64, verbose_name='Marca:')),
                ('serial', models.CharField(default='', max_length=64, verbose_name='Serial:')),
                ('cantidad', models.CharField(default='', max_length=64, verbose_name='Cantidad:')),
                ('valor', models.CharField(default='', max_length=64, verbose_name='Valor:')),
                ('condicion', models.CharField(default='', max_length=64, verbose_name='Condición:')),
                ('ubicacion', models.CharField(default='', max_length=64, verbose_name='Ubicación:')),
                ('fecha_adq', models.DateField(verbose_name='Fecha')),
                ('garantia', models.CharField(default='', max_length=64, verbose_name='Garantía:')),
                ('observaciones', models.TextField(default='', max_length=64, verbose_name='Garantía:')),
                ('codigo_bn', models.CharField(default='', max_length=64, verbose_name='Garantía:')),
            ],
        ),
    ]
