# Generated by Django 5.0.3 on 2024-07-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumible',
            name='observaciones',
            field=models.TextField(default='', max_length=64, verbose_name='Observaciones:'),
        ),
    ]
