# Generated by Django 5.0.3 on 2024-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_consumible_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='articulo',
            field=models.CharField(default='', max_length=64, verbose_name='Articulo:'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='cantidad',
            field=models.CharField(default='', max_length=64, verbose_name='Cantidad:'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='departamento',
            field=models.CharField(default='', max_length=64, verbose_name='Departamento:'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='descripcion',
            field=models.CharField(default='', max_length=64, verbose_name='Descripción:'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='inventario',
            field=models.CharField(default='', max_length=64, verbose_name='Inventario:'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='observaciones',
            field=models.CharField(default='', max_length=64, verbose_name='Observaciones:'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='codigo_bn',
            field=models.CharField(default='', max_length=64, verbose_name='Código BN:'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='numero_orden',
            field=models.CharField(default='', max_length=64, verbose_name='Número de orden:'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='producto',
            field=models.TextField(default='', max_length=64, verbose_name='Producto:'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='proveedor',
            field=models.CharField(default='', max_length=64, verbose_name='Proveedor:'),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='codigo_bn',
            field=models.CharField(default='', max_length=64, verbose_name='Código BN:'),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='observaciones',
            field=models.TextField(default='', max_length=64, verbose_name='Observaciones:'),
        ),
    ]
