# Generated by Django 5.0.1 on 2024-01-10 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
