# Generated by Django 5.0.1 on 2024-01-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergency_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='denuciante',
            new_name='denunciante',
        ),
    ]
