# Generated by Django 5.0.1 on 2024-01-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_rename_denuciante_emergency_denunciante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='telefono_denuciante',
            new_name='telefono_denunciante',
        ),
    ]
