# Generated by Django 5.0.1 on 2024-01-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_rename_telefono_denuciante_emergency_telefono_denunciante'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
