# Generated by Django 4.2.7 on 2024-06-28 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency', '0005_emergency_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencias', to=settings.AUTH_USER_MODEL),
        ),
    ]
