# Generated by Django 4.2.7 on 2024-06-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonoGuerra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'bonoguerra',
                'verbose_name_plural': 'bonosguerras',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='CestaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'cestaticket',
                'verbose_name_plural': 'cestatickets',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'estado_civil',
                'verbose_name_plural': 'estados_civiles',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_instruccion', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'grado_instruccion',
                'verbose_name_plural': 'grados_instruccion',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'nacionalidad',
                'verbose_name_plural': 'nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=11)),
                ('conyugue', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_conyugue', models.IntegerField(blank=True, null=True)),
                ('discapacitado', models.BooleanField()),
                ('direccion', models.CharField(max_length=150)),
                ('nro_cuenta', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estudias', models.BooleanField()),
                ('comision_servicio', models.BooleanField()),
                ('pnb', models.BooleanField()),
                ('fecha_ingreso_911', models.DateField()),
                ('fecha_ingreso_apn', models.DateField()),
                ('contratos', models.IntegerField()),
                ('nino_menor_12', models.CharField(blank=True, max_length=2, null=True)),
                ('edades1', models.IntegerField(blank=True, null=True)),
                ('hijos_13_18', models.CharField(blank=True, max_length=2, null=True)),
                ('edades2', models.IntegerField(blank=True, null=True)),
                ('nina_menor_12', models.CharField(blank=True, max_length=2, null=True)),
                ('edades3', models.IntegerField(blank=True, null=True)),
                ('hijos_discapacidad', models.CharField(blank=True, max_length=2, null=True)),
                ('edades4', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_retiro', models.DateField(blank=True, default='', null=True)),
                ('fasmij', models.BooleanField()),
                ('parentezco1', models.CharField(blank=True, max_length=10, null=True)),
                ('beneficiario1', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula1', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion1', models.CharField(blank=True, max_length=150, null=True)),
                ('parentezco2', models.CharField(blank=True, max_length=10, null=True)),
                ('beneficiario2', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula2', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion2', models.CharField(blank=True, max_length=150, null=True)),
                ('parentezco3', models.CharField(blank=True, max_length=10, null=True)),
                ('beneficiario3', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula3', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion3', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.departamento')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.estadocivil')),
                ('grado_instruccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.grado')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.nacionalidad')),
            ],
            options={
                'verbose_name': 'personal',
                'verbose_name_plural': 'personales',
            },
        ),
        migrations.CreateModel(
            name='Sangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tipo_sangre',
                'verbose_name_plural': 'tipos_sangre',
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('sede', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sexo',
                'verbose_name_plural': 'sexos',
            },
        ),
        migrations.CreateModel(
            name='SueldoMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'sueldominimo',
                'verbose_name_plural': 'sueldosminimo',
            },
        ),
        migrations.CreateModel(
            name='TallasCamisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('talla_camisa', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'talla_camisa',
                'verbose_name_plural': 'tallas_camisas',
            },
        ),
        migrations.CreateModel(
            name='TallasPantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('talla_pantalon', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'talla_pantalon',
                'verbose_name_plural': 'tallas_pantalones',
            },
        ),
        migrations.CreateModel(
            name='TallasZapatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('talla_zapato', models.CharField(max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'talla_zapato',
                'verbose_name_plural': 'tallas_zapatos',
            },
        ),
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'tasabcv',
                'verbose_name_plural': 'tasasbcv',
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_personal', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tipo_personal',
                'verbose_name_plural': 'tipos_personales',
            },
        ),
        migrations.CreateModel(
            name='Sueldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('sueldo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prima_profesionalismo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_discapacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_hijos_menor_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_hijas_menor_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_hijos_12_18', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_hijos_discapacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('n_fasmij', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cesta_t', models.BooleanField()),
                ('b_guerra', models.BooleanField()),
                ('monto_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.bonoguerra')),
                ('monto_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.cestaticket')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.personal')),
            ],
            options={
                'verbose_name': 'sueldo',
                'verbose_name_plural': 'sueldos',
            },
        ),
        migrations.CreateModel(
            name='PrimaProfesionalismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.grado')),
            ],
            options={
                'verbose_name': 'prima_profesional',
                'verbose_name_plural': 'primas_prosesionales',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.sedes'),
        ),
        migrations.AddField(
            model_name='personal',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.sexo'),
        ),
        migrations.AddField(
            model_name='personal',
            name='talla_camisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tallascamisa'),
        ),
        migrations.AddField(
            model_name='personal',
            name='talla_pantalon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tallaspantalon'),
        ),
        migrations.AddField(
            model_name='personal',
            name='talla_zapato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tallaszapatos'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tipopersonal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_sangre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.sangre'),
        ),
        migrations.CreateModel(
            name='Bienes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.departamento')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.sedes')),
            ],
            options={
                'verbose_name': 'bien',
                'verbose_name_plural': 'bienes',
            },
        ),
    ]
