# Generated by Django 4.2.7 on 2024-06-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='nina_menor_12',
            new_name='ninaaaaa_menor_12',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='nino_menor_12',
            new_name='ninooooo_menor_12',
        ),
    ]
