# Generated by Django 4.2.7 on 2024-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_rename_nina_menor_12_personal_ninaaaaa_menor_12_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='ninaaaaa_menor_12',
            new_name='nina_menor_12',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='ninooooo_menor_12',
        ),
        migrations.AddField(
            model_name='personal',
            name='nino_menor_12',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
