# Generated by Django 5.0.6 on 2024-05-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='', max_length=64, verbose_name='Estado:')),
                ('informativa', models.CharField(default='', max_length=64, verbose_name='Informativa:')),
                ('falsa', models.CharField(default='', max_length=64, verbose_name='Falsa:')),
                ('realesno', models.CharField(default='', max_length=64, verbose_name='Reales no Efectivas:')),
                ('realesf', models.CharField(default='', max_length=64, verbose_name='Reales Efectivas:')),
                ('videop', models.CharField(default='', max_length=64, verbose_name='Video Protección:')),
            ],
        ),
    ]
