# Generated by Django 5.0.1 on 2024-06-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_llamadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadas',
            name='mes',
            field=models.CharField(default='', max_length=64, verbose_name='Mes:'),
        ),
    ]
