# Generated by Django 5.0.1 on 2024-07-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_llamadas_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(default='', max_length=64, verbose_name='Mes:')),
                ('estado', models.CharField(default='', max_length=64, verbose_name='Estado:')),
                ('mantenimiento_preventivo', models.CharField(default='', max_length=64, verbose_name='Mantemiento Preventivo:')),
                ('mantenimiento_plantas', models.CharField(default='', max_length=64, verbose_name='Mantemiento de Plantas:')),
                ('mantenimiento_general', models.CharField(default='', max_length=64, verbose_name='Mantemiento General:')),
                ('reparacion', models.CharField(default='', max_length=64, verbose_name='Reparación:')),
            ],
        ),
    ]
