# Generated by Django 5.0.1 on 2024-07-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_infraestructura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraestructura',
            name='mantenimiento_general',
        ),
        migrations.RemoveField(
            model_name='infraestructura',
            name='mantenimiento_plantas',
        ),
        migrations.RemoveField(
            model_name='infraestructura',
            name='mantenimiento_preventivo',
        ),
        migrations.RemoveField(
            model_name='infraestructura',
            name='reparacion',
        ),
        migrations.AddField(
            model_name='infraestructura',
            name='cantidad',
            field=models.CharField(default='', max_length=64, verbose_name='Cantidad:'),
        ),
        migrations.AddField(
            model_name='infraestructura',
            name='infraestructura',
            field=models.CharField(default='', max_length=64, verbose_name='Infraestrutuctura:'),
        ),
    ]
