# Generated by Django 5.0.6 on 2024-06-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paneluser", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfileEntity",
        ),
    ]
