# Generated by Django 5.0.6 on 2024-05-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneluser', '0002_usuarios_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(default='', max_length=200, verbose_name='Tipo:'),
        ),
    ]
