# Generated by Django 4.2.7 on 2024-06-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(verbose_name='Fecha de Atención')),
                ('nroreporte', models.CharField(max_length=10)),
                ('diareporte', models.CharField(max_length=10)),
                ('placa', models.CharField(max_length=10)),
                ('institucion', models.CharField(max_length=300)),
                ('tipounidad', models.CharField(max_length=10)),
                ('num_interna', models.CharField(max_length=10)),
                ('nombre', models.CharField(default='', max_length=300)),
                ('apellido', models.CharField(default='', max_length=300)),
                ('genero', models.CharField(default='', max_length=300)),
                ('cedula', models.CharField(default='', max_length=300)),
                ('nro_telefono', models.CharField(default='', max_length=10)),
                ('direccion_paciente', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name': 'uri',
                'verbose_name_plural': 'uris',
            },
        ),
    ]
