# Generated by Django 4.2.7 on 2024-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0003_traslado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'via_reporte',
                'verbose_name_plural': 'via_reportes',
            },
        ),
    ]
