# Generated by Django 4.2.7 on 2024-06-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0006_enfrentamiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enfrentamiento',
        ),
    ]
