# Generated by Django 4.2.7 on 2024-06-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0007_delete_enfrentamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arma', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tipo_arma',
                'verbose_name_plural': 'tipo_armas',
            },
        ),
    ]
