# Generated by Django 4.2.7 on 2024-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0008_tipo_arma'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accidente', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tipo_accidente',
                'verbose_name_plural': 'tipo_accidentes',
            },
        ),
    ]
