# Generated by Django 4.2.7 on 2024-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0011_colorpiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaturaPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_piel', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'temperatura_piel',
                'verbose_name_plural': 'temperatura_pieles',
            },
        ),
    ]
