# Generated by Django 4.2.7 on 2024-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0012_temperaturapiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumedadPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_piel', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'humedad_piel',
                'verbose_name_plural': 'humedad_pieles',
            },
        ),
    ]
