# Generated by Django 4.2.7 on 2024-07-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0014_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervencion', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'intervencion',
                'verbose_name_plural': 'intervenciones',
            },
        ),
    ]
