# Generated by Django 4.2.7 on 2024-07-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0016_contactopaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactopaciente',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
    ]
