# Generated by Django 4.2.7 on 2024-07-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0017_alter_contactopaciente_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoContactoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_contacto', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'no_contacto',
                'verbose_name_plural': 'no_contactos',
            },
        ),
    ]
