# Generated by Django 4.2.7 on 2024-07-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0018_nocontactopaciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uri',
        ),
    ]
