# Generated by Django 4.2.7 on 2024-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0024_unidadrespuestainmediata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='accidenteVehicular',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='apellidoAcompanante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='apellidoTestigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='calleEvento',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='casaEvento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='causa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='cedulaAcompanante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='cedulaConductor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='cedulaMedico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='cedulaSupervisor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='cedulaTecnico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='cedulaTestigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='cedulaTripulante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='centroAsistencial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='conductorUnidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='descripcionAdicional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='descripcionAdicionalResultado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='direccionAcompanante',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='direccionTestigo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='direccion_paciente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='dosis1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='dosis2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='dosis3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='ecgM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='ecgO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='ecgTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='ecgV',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='edadAcompanate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='edadTestigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='ejeEvento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='escalaGlasgow',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='fecha_atencion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Atención'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='firma1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='firma2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='firma3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='frecuenciaCardiaca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='frecuenciaRespiratoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='glicemiaCapilar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='hora1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='hora2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='hora3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='horaAlarma',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='horaLlegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='horaLlegadaHosp',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='horaMedicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='horaSalida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='horaSede',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='hospitalDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='hospitalOrigen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='institucion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='jefecomision1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='jefecomision2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='jefecomision3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='llenadoCapilar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='medicamento1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='medicamento2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='medicamento3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='medicoGuardia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='medicoRecibe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='medicoRefiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='msos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='nombreAcompanante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='nombreTestigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='nro_telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='nroreporte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='num_interna',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='observacionesNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='observacionesServicio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='observacionesSustancia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='organismo1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='organismo2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='organismo3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='parentezcoAcompanante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='pisoEvento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='preexistencias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='presionArterial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='referenciaEvento',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='resultadoEvaluacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='sectorEvento',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='selloMsds',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='servicioAsistencial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='signosSintomas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='spo2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='supervisorGuardia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='tecnicoEmergencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='telefonoAcompanate',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='telefonoTestigo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='temperatura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='tercerTripulante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='tiempoServicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='tipounidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='transferenciaEmergencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='ultimaComida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='unidadplaca1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='unidadplaca2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='unidadplaca3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
