# Generated by Django 5.0.1 on 2024-07-05 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_rename_ninaaaaa_menor_12_personal_nina_menor_12_and_more'),
        ('uri', '0025_alter_unidadrespuestainmediata_accidentevehicular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='alergias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='colorPiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.colorpiel'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='contactoNoPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.nocontactopaciente'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='contactoPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.contactopaciente'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='diareporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.diasemana'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='emergenciaMedica',
            field=models.ManyToManyField(blank=True, null=True, to='uri.emergencianotraumaticas'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='estadoEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.estados'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.evaluacion'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='evaluacionResp',
            field=models.ManyToManyField(blank=True, null=True, to='uri.evaluacionrespiracion'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uris_genero', to='rrhh.sexo'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='generoAcompanante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uris_genero_acompanante', to='rrhh.sexo'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='hipotermiaopcion',
            field=models.ManyToManyField(blank=True, null=True, to='uri.hipotermiaopcion'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='horaSalidaHosp',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='humedadPiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.humedadpiel'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='intervencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.intervenciones'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='intervencionResp',
            field=models.ManyToManyField(blank=True, null=True, to='uri.intervencionrespiracion'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='lugarAtencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.lugares'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='maniobraPelvis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.maniobrapelvis'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='modotraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.traslado'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='municipioEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.municipios'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='parroquiaEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.parroquias'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='reaccionPupilar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.reaccionpupilar'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.resultados'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='resultadoResp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.resultadirespiracion'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='temperaturaPiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.temperaturapiel'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='tipoAccidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.tipoaccidente'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='tipoArma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.tipo_arma'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='tipoServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.servicios'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='traumaNoIntencional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.traumanointencional'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='traumaVehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.traumavehiculo'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='viaReporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.reportes'),
        ),
        migrations.AlterField(
            model_name='unidadrespuestainmediata',
            name='viajaba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uri.viajaba'),
        ),
    ]
