# Generated by Django 4.2.7 on 2024-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=300)),
                ('sede', models.CharField(max_length=300)),
                ('departamento', models.CharField(max_length=300)),
                ('tipoincidencia', models.CharField(max_length=300)),
                ('usuario', models.CharField(max_length=300)),
                ('observaciones', models.CharField(max_length=300)),
                ('tiposolicitud', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name': 'incidencia',
                'verbose_name_plural': 'incidencias',
            },
        ),
    ]
