# Generated by Django 4.2.7 on 2024-06-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='tiposolicitud',
            field=models.CharField(max_length=350),
        ),
    ]
