# Generated by Django 5.1.1 on 2025-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='tipo',
            field=models.CharField(choices=[('act', 'Activo'), ('ina', 'Inactivo'), ('inv', 'Invalido'), ('cer', 'Cerrado')], max_length=64),
        ),
    ]
