# Generated by Django 5.1.1 on 2025-02-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_gestion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='tipo',
            field=models.CharField(default='', max_length=64, verbose_name='Tipo de Incidente:'),
        ),
    ]
