# Generated by Django 5.1.1 on 2025-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_alter_gestion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='descripcion',
            field=models.CharField(choices=[('Improvisto - R', 'Improvisto - R'), ('Accidente familiar - R', 'Accidente familiar - R'), ('Accidente laboral - R', 'Accidente laboral - R'), ('Retiro por renuncia - R', 'Retiro por renuncia - R'), ('Retiro por despido - R', 'Retiro por despido - R'), ('Confrontamiento entre personal', 'Confrontamiento entre personal'), ('Hurto o pErdida de bienes', 'Hurto o pérdida de bienes'), ('Confrontamiento entre personal o natural', 'Confrontamiento entre personal o natural')], max_length=64),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipo',
            field=models.CharField(choices=[('Retiro - R', 'Retiro - R'), ('Conflictos - C', 'Conflictos - C'), ('Conflictos ajenos - CA', 'Conflictos ajenos - CA')], max_length=64),
        ),
    ]
