# Generated by Django 5.1.1 on 2025-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_alter_gestion_descripcion_alter_gestion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='descripcion',
            field=models.CharField(choices=[('Improvisto - R', 'Improvisto - R'), ('Accidente familiar - R', 'Accidente familiar - R'), ('Accidente laboral - R', 'Accidente laboral - R'), ('Retiro por renuncia - R', 'Retiro por renuncia - R'), ('Retiro por despido - R', 'Retiro por despido - R'), ('Confrontamiento entre personal - CA', 'Confrontamiento entre personal - CA'), ('Hurto o pErdida de bienes - CA', 'Hurto o pérdida de bienes - CA'), ('Confrontamiento entre personal o natural - CA', 'Confrontamiento entre personal o natural - CA')], max_length=64),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='motivo',
            field=models.CharField(choices=[('Salida', 'Salida'), ('Entrada', 'Entrada')], max_length=64),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vehiculo',
            field=models.CharField(choices=[('Patrulla', 'Patrulla'), ('Particular', 'Particular'), ('Ambulancia', 'Ambulancia')], max_length=64),
        ),
    ]
