# Generated by Django 5.1.1 on 2025-02-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_alter_gestion_descripcion_alter_vehiculo_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vehiculo',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Patrulla', 'Patrulla'), ('Ambulancia', 'Ambulancia')], max_length=64),
        ),
    ]
