# Generated by Django 5.1.1 on 2025-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_alter_vehiculo_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='motivo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=64),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vehiculo',
            field=models.CharField(choices=[('Patrulla', 'Patrulla'), ('Particular', 'Particular'), ('Ambulancia', 'Ambulancia')], max_length=64),
        ),
    ]
