# Generated by Django 5.0.6 on 2024-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Está eliminado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminado el"
                    ),
                ),
                (
                    "denunciante",
                    models.CharField(max_length=150, verbose_name="Denunciante"),
                ),
                (
                    "telefono_denunciante",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        verbose_name="Telefono del Denunciante",
                    ),
                ),
                (
                    "direccion_incidencia",
                    models.TextField(
                        blank=True, verbose_name="Dirección de la Incidencia"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "datecompleted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergencia",
                "verbose_name_plural": "Emergencias",
                "db_table": "eme_emergencia",
                "ordering": ["incidencia_id"],
            },
        ),
        migrations.CreateModel(
            name="IncidenciaEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(max_length=180, verbose_name="Tipo de Incidencia"),
                ),
            ],
            options={
                "verbose_name": "Incidencia",
                "verbose_name_plural": "Incidencias",
                "db_table": "eme_incidencia",
                "ordering": ["tipo"],
            },
        ),
        migrations.CreateModel(
            name="OrganismoCompetenteEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=180, verbose_name="Nombre del organismo competente"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organismo Competente",
                "verbose_name_plural": "Organismo Competentes",
                "db_table": "eme_organismo_competente",
                "ordering": ["nombre"],
            },
        ),
    ]
