# Generated by Django 5.0.6 on 2024-06-11 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("index", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuadrantePaz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="IncidenciaEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(max_length=180, verbose_name="Tipo de Incidencia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganismoCompetente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OrganismoCompetenteEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=180, verbose_name="Nombre del organismo competente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "id_estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eme.estado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Está eliminado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminado el"
                    ),
                ),
                (
                    "denunciante",
                    models.CharField(max_length=150, verbose_name="Denunciante"),
                ),
                (
                    "telefono_denunciante",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        verbose_name="Telefono del Denunciante",
                    ),
                ),
                (
                    "direccion_incidencia",
                    models.TextField(
                        blank=True, verbose_name="Dirección de la Incidencia"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "datecompleted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalizacion"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_delete",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eliminado por",
                    ),
                ),
                (
                    "parroquia_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.parroquiaentity",
                        verbose_name="Parroquia",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "incidencia_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eme.incidenciaentity",
                        verbose_name="Incidencia",
                    ),
                ),
                (
                    "organismo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eme.organismocompetenteentity",
                        verbose_name="Organismo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergencia",
                "verbose_name_plural": "Emergencias",
                "db_table": "eme_emergencia",
                "ordering": ["incidencia_id"],
            },
        ),
        migrations.CreateModel(
            name="Parroquia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "id_cuadrante_paz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eme.cuadrantepaz",
                    ),
                ),
                (
                    "id_estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eme.estado"
                    ),
                ),
                (
                    "id_municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eme.municipio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emergency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="Está eliminado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminado el"
                    ),
                ),
                ("denunciante", models.CharField(max_length=255)),
                ("telefono_denunciante", models.CharField(blank=True, max_length=255)),
                ("direccion_incidencia", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("datecompleted", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_delete",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eliminado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "id_estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eme.estado"
                    ),
                ),
                (
                    "id_incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eme.incidencia"
                    ),
                ),
                (
                    "id_municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eme.municipio"
                    ),
                ),
                (
                    "id_organismo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eme.organismocompetente",
                    ),
                ),
                (
                    "id_parroquia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eme.parroquia"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
