# Generated by Django 5.0.6 on 2024-06-18 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eme", "0001_initial"),
        ("index", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyentity",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="emergencyentity",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_delete",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="emergencyentity",
            name="parroquia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="index.parroquiaentity",
                verbose_name="Parroquia",
            ),
        ),
        migrations.AddField(
            model_name="emergencyentity",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="emergencyentity",
            name="incidencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eme.incidenciaentity",
                verbose_name="Incidencia",
            ),
        ),
        migrations.AddField(
            model_name="emergencyentity",
            name="organismo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eme.organismocompetenteentity",
                verbose_name="Organismo",
            ),
        ),
    ]
